version: '3.5'

services:
    jenkins:
        user: root
        container_name: 'jenkins'
        build: .
        restart: always
        ports:
            - "${HTTP_PORT}:8080"
            - "${AGENT_PORT}:50000"
        volumes:
            - ~/jenkins:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
